/**
 * RPC Request Handler
 *
 * Handles all incoming RPC requests to the Snap
 */

import { Json } from '@metamask/snaps-sdk';
import { SecuritizationService } from '../services/securitization';
import { MockStorageService } from '../services/storage';
import { Logger } from '../utils/logger';
import { validatePrivateKey, validateAddress, validatePin } from '../utils/validation';
import type {
  SecuritizeRequest,
  RecoverRequest,
} from '../types';

const logger = new Logger('RpcHandler');

/**
 * Main RPC request handler
 */
export async function handleRpcRequest(
  _origin: string,
  request: { method: string; params?: Json },
): Promise<Json> {
  switch (request.method) {
    case 'shard_getVersion':
      return handleGetVersion();

    case 'shard_generateWallet':
      return handleGenerateWallet();

    case 'shard_securitize':
      return handleSecuritize(request.params as unknown as SecuritizeRequest);

    case 'shard_recover':
      return handleRecover(request.params as unknown as RecoverRequest);

    case 'shard_checkHealth':
      return handleHealthCheck();

    case 'shard_getState':
      return handleGetState();

    default:
      throw new Error(`Method not supported: ${request.method}`);
  }
}

/**
 * Get Snap version
 */
async function handleGetVersion(): Promise<Json> {
  return {
    version: '1.0.0',
  } as Json;
}

/**
 * Generate a new wallet and auto-securitize it
 */
async function handleGenerateWallet(): Promise<Json> {
  logger.info('Generating new wallet...');

  try {
    // Generate random 32-byte private key
    const privateKeyBytes = new Uint8Array(32);
    crypto.getRandomValues(privateKeyBytes);

    // Convert to hex string with 0x prefix
    const privateKey = '0x' + Array.from(privateKeyBytes)
      .map(b => b.toString(16).padStart(2, '0'))
      .join('');

    // Derive Ethereum address from private key
    // For now, use a simplified derivation (in production, use proper ECDSA)
    // We'll use the last 20 bytes of keccak256(publicKey) as the address
    // For this MVP, we'll generate a placeholder address
    const addressBytes = new Uint8Array(20);
    crypto.getRandomValues(addressBytes);
    const walletAddress = '0x' + Array.from(addressBytes)
      .map(b => b.toString(16).padStart(2, '0'))
      .join('');

    logger.info('Generated wallet address:', walletAddress);

    // Auto-securitize the wallet
    const securitizationService = new SecuritizationService();
    const storageService = new MockStorageService();

    const result = await securitizationService.securitize(privateKey);
    await storageService.distributeShards(result, walletAddress);

    // Update snap state
    const state = await snap.request({
      method: 'snap_manageState',
      params: { operation: 'get' },
    });

    await snap.request({
      method: 'snap_manageState',
      params: {
        operation: 'update',
        newState: {
          ...(state as object),
          wallets: {
            ...(state as any)?.wallets,
            [walletAddress]: {
              securitized: true,
              timestamp: Date.now(),
              shardLocations: ['sim', 'yubikey', 'custodial', 'escrow'],
              generated: true, // Mark as generated by Snap
            },
          },
        },
      },
    });

    // Check health after distribution
    const healthStatus = await storageService.checkHealth();

    console.log('[Shard Snap] New wallet generated and securitized:', walletAddress);

    return {
      success: true,
      message: 'New wallet generated and securitized successfully',
      walletAddress,
      privateKey, // Return so user can import to MetaMask
      healthStatus,
    } as unknown as Json;
  } catch (error) {
    console.error('[Shard Snap] Wallet generation failed:', error);
    return {
      success: false,
      message: `Wallet generation failed: ${(error as Error).message}`,
    } as Json;
  }
}

/**
 * Securitize a private key
 */
async function handleSecuritize(
  params: SecuritizeRequest,
): Promise<Json> {
  const { privateKey, walletAddress } = params;

  // Validate required parameters
  if (!privateKey || !walletAddress) {
    logger.error('Missing required parameters');
    throw new Error('Missing required parameters: privateKey, walletAddress');
  }

  // Validate private key
  const pkValidation = validatePrivateKey(privateKey);
  if (!pkValidation.valid) {
    logger.error('Invalid private key:', pkValidation.error);
    throw new Error(`Invalid private key: ${pkValidation.error}`);
  }

  // Validate wallet address
  const addrValidation = validateAddress(walletAddress);
  if (!addrValidation.valid) {
    logger.error('Invalid wallet address:', addrValidation.error);
    throw new Error(`Invalid wallet address: ${addrValidation.error}`);
  }

  logger.info('Securitizing wallet:', walletAddress);

  try {
    const securitizationService = new SecuritizationService();
    const storageService = new MockStorageService();

    // Perform securitization
    const result = await securitizationService.securitize(privateKey);

    // Distribute shards to mock storage
    await storageService.distributeShards(result, walletAddress);

    // Update snap state
    const state = await snap.request({
      method: 'snap_manageState',
      params: { operation: 'get' },
    });

    await snap.request({
      method: 'snap_manageState',
      params: {
        operation: 'update',
        newState: {
          ...(state as object),
          wallets: {
            ...(state as any)?.wallets,
            [walletAddress]: {
              securitized: true,
              timestamp: Date.now(),
              shardLocations: ['sim', 'yubikey', 'custodial', 'escrow'],
            },
          },
        },
      },
    });

    // Check health after distribution
    const healthStatus = await storageService.checkHealth();

    console.log('[Shard Snap] Securitization complete for', walletAddress);

    return {
      success: true,
      message: 'Wallet securitized successfully',
      healthStatus,
    } as unknown as Json;
  } catch (error) {
    console.error('[Shard Snap] Securitization failed:', error);
    return {
      success: false,
      message: `Securitization failed: ${(error as Error).message}`,
    } as Json;
  }
}

/**
 * Recover a private key from shards
 */
async function handleRecover(
  params: RecoverRequest,
): Promise<Json> {
  const { walletAddress } = params;

  // Validate required parameters
  if (!walletAddress) {
    logger.error('Missing required parameters');
    throw new Error('Missing required parameters: walletAddress');
  }

  // Validate wallet address
  const addrValidation = validateAddress(walletAddress);
  if (!addrValidation.valid) {
    logger.error('Invalid wallet address:', addrValidation.error);
    throw new Error(`Invalid wallet address: ${addrValidation.error}`);
  }

  logger.info('Recovering wallet:', walletAddress);

  try {
    const securitizationService = new SecuritizationService();
    const storageService = new MockStorageService();

    // Retrieve shards from storage
    const shards = await storageService.retrieveShards(walletAddress);

    if (shards.length < 2) {
      throw new Error(`Insufficient shards: found ${shards.length}, need 2`);
    }

    // Retrieve the encrypted secret
    const encryptedSecret = await storageService.retrieveEncryptedSecret(walletAddress);

    if (!encryptedSecret) {
      throw new Error('Encrypted secret not found for this wallet');
    }

    // Recover private key
    const privateKey = await securitizationService.recover(shards, encryptedSecret);

    console.log('[Shard Snap] Recovery complete for', walletAddress);

    return {
      success: true,
      privateKey,
    } as Json;
  } catch (error) {
    console.error('[Shard Snap] Recovery failed:', error);
    return {
      success: false,
      error: (error as Error).message,
    } as Json;
  }
}

/**
 * Perform manual health check
 */
async function handleHealthCheck(): Promise<Json> {
  console.log('[Shard Snap] Performing manual health check...');

  const storageService = new MockStorageService();
  const healthStatus = await storageService.checkHealth();

  const recommendations = generateRecommendations(healthStatus);

  // Update state with latest health status
  const state = await snap.request({
    method: 'snap_manageState',
    params: { operation: 'get' },
  });

  await snap.request({
    method: 'snap_manageState',
    params: {
      operation: 'update',
      newState: {
        ...(state as object),
        lastHealthCheck: Date.now(),
        healthStatus: healthStatus as any,
      },
    },
  });

  return {
    timestamp: Date.now(),
    status: healthStatus.overall,
    details: {
      sim: healthStatus.sim.status,
      yubikey: healthStatus.yubikey.status,
      custodial: healthStatus.custodial.status,
      escrow: healthStatus.escrow.status,
    },
    recommendations,
  } as Json;
}

/**
 * Get current snap state
 */
async function handleGetState(): Promise<Json> {
  const state = await snap.request({
    method: 'snap_manageState',
    params: { operation: 'get' },
  });

  return state || {};
}

/**
 * Generate health recommendations
 */
function generateRecommendations(healthStatus: any): string[] {
  const recommendations: string[] = [];

  if (healthStatus.sim.status !== 'healthy') {
    recommendations.push('Restore SIM card shard');
  }
  if (healthStatus.yubikey.status !== 'healthy') {
    recommendations.push('Check YubiKey connection');
  }
  if (healthStatus.custodial.status !== 'healthy') {
    recommendations.push('Contact custodial service');
  }
  if (healthStatus.escrow.status !== 'healthy') {
    recommendations.push('Check escrow service status');
  }

  if (recommendations.length === 0) {
    recommendations.push('All storage locations healthy');
  }

  return recommendations;
}
